// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Certificador.DAL.Api.Entities;

[Index("NIT", Name = "uq_cliente_nit", IsUnique = true)]
public partial class ClienteAPI
{
    [Key]
    public int IdCliente { get; set; }

    [Required]
    [StringLength(150)]
    public string NombreCliente { get; set; }

    [Required]
    [StringLength(20)]
    public string NIT { get; set; }

    [Required]
    [StringLength(255)]
    public string ApiKeyHash { get; set; }

    [Required]
    public bool? EstadoCliente { get; set; }

    public bool EstadoPago { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime CreadoEn { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime ActualizadoEn { get; set; }

    [InverseProperty("IdClienteNavigation")]
    public virtual ICollection<Factura> factura { get; set; } = new List<Factura>();
}