// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Certificador.DAL.Api.Entities;

[Index("IdFactura", Name = "fk_facturacert_factura")]
[Index("NumeroAutorizacion", Name = "uq_numero_autorizacion", IsUnique = true)]
[Index("Serie", "Correlativo", Name = "uq_serie_correlativo", IsUnique = true)]
public partial class facturacertificada
{
    [Key]
    public int IdFacturaCertificada { get; set; }

    public int IdFactura { get; set; }

    public Guid NumeroAutorizacion { get; set; }

    [Required]
    [StringLength(20)]
    public string Serie { get; set; }

    public int Correlativo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime FechaCertificacion { get; set; }

    [Required]
    public bool? Estado { get; set; }

    [ForeignKey("IdFactura")]
    [InverseProperty("facturacertificada")]
    public virtual factura IdFacturaNavigation { get; set; }
}