// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Certificador.DAL.Api.Entities;

[Index("NumeroAutorizacion", Name = "uq_autorizacion", IsUnique = true)]
[Index("IdCliente", "IdempotenciaKey", Name = "uq_idem", IsUnique = true)]
public partial class Factura
{
    [Key]
    public int IdFactura { get; set; }

    public int IdCliente { get; set; }

    [Required]
    [StringLength(64)]
    public string FacturaExternaId { get; set; }

    [Required]
    [StringLength(64)]
    public string IdempotenciaKey { get; set; }

    [Required]
    [Column(TypeName = "json")]
    public string DataOriginal { get; set; }

    public bool Estado { get; set; }

    [StringLength(64)]
    public string ErrorCodigo { get; set; }

    [StringLength(400)]
    public string ErrorMensaje { get; set; }

    public Guid? NumeroAutorizacion { get; set; }

    [StringLength(20)]
    public string Serie { get; set; }

    public int? Correlativo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? FechaCertificacion { get; set; }

    [Precision(12, 2)]
    public decimal? MontoTotal { get; set; }

    [StringLength(250)]
    public string AnulacionMotivo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? FechaAnulacion { get; set; }

    [Required]
    public bool? Activo { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime CreadoEn { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime ActualizadoEn { get; set; }

    [ForeignKey("IdCliente")]
    [InverseProperty("factura")]
    public virtual ClienteAPI IdClienteNavigation { get; set; }

    [InverseProperty("IdFacturaNavigation")]
    public virtual ICollection<FacturaCertificada> facturacertificada { get; set; } = new List<FacturaCertificada>();
}