// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Certificador.DAL.Api.Entities;
using Microsoft.EntityFrameworkCore;

namespace Certificador.DAL.Api;

public partial class CERTIFICADORContext : DbContext
{
    public CERTIFICADORContext(DbContextOptions<CERTIFICADORContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ClienteAPI> ClienteAPI { get; set; }

    public virtual DbSet<Factura> Factura { get; set; }

    public virtual DbSet<FacturaCertificada> FacturaCertificada { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_0900_ai_ci")
            .HasCharSet("utf8mb4");

        modelBuilder.Entity<ClienteAPI>(entity =>
        {
            entity.HasKey(e => e.IdCliente).HasName("PRIMARY");

            entity.Property(e => e.ActualizadoEn)
                .ValueGeneratedOnAddOrUpdate()
                .HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.CreadoEn).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.EstadoCliente).HasDefaultValueSql("'1'");
        });

        modelBuilder.Entity<Factura>(entity =>
        {
            entity.HasKey(e => e.IdFactura).HasName("PRIMARY");

            entity.Property(e => e.Activo).HasDefaultValueSql("'1'");
            entity.Property(e => e.ActualizadoEn)
                .ValueGeneratedOnAddOrUpdate()
                .HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.CreadoEn).HasDefaultValueSql("CURRENT_TIMESTAMP");

            entity.HasOne(d => d.IdClienteNavigation).WithMany(p => p.factura)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_fact_cliente");
        });

        modelBuilder.Entity<FacturaCertificada>(entity =>
        {
            entity.HasKey(e => e.IdFacturaCertificada).HasName("PRIMARY");

            entity.Property(e => e.Estado).HasDefaultValueSql("'1'");
            entity.Property(e => e.FechaCertificacion).HasDefaultValueSql("CURRENT_TIMESTAMP");

            entity.HasOne(d => d.IdFacturaNavigation).WithMany(p => p.facturacertificada).HasConstraintName("fk_facturacert_factura");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}